package:
  name: tiangan
  version: "0.1.40"

source:
  path: .

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10

test:
  imports:
    - tiangan

about:
  home: "https://github.com/dbugpro/tiangan"
  license: "MIT"
  summary: "TIANGAN: A Python package for Chinese Heavenly Stems and Earthly Branches."

