[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tiangan"
version = "0.1.0"
description = "The Tiangan Python package."
authors = [
    { name = "DBUG" }
]
readme = "README.md"
requires-python = ">=3.8"

[project.urls]
Home = "https://anaconda.org/dbx"
