package:
  name: tiangan
  version: "0.1.0"

source:
  path: ../

build:
  noarch: python
  script: python -m pip install .

requirements:
  host:
    - python
    - pip
  run:
    - python

about:
  home: https://anaconda.org/dbx
  license: MIT
  summary: "The Tiangan Python package."

extra:
  recipe-maintainers:
    - dbugx
