name: Build and Publish Conda Package

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install micromamba
        uses: mamba-org/provision-with-micromamba@v15
        with:
          micromamba-version: "latest"

      - name: Create build environment
        run: |
          micromamba create -y -n build-env conda-build anaconda-client python=3.11
          micromamba activate build-env

      - name: Build Conda package
        run: |
          micromamba activate build-env
          conda build recipe --output-folder conda-dist

      - name: Upload to Anaconda
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          micromamba activate build-env
          anaconda upload conda-dist/**/tiangan-*.tar.bz2 --label main
